version: '3'
services:

#  echo:
#    build: .
#    command: ["-d", "1"]

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./hello.conf:/etc/nginx/conf.d/hello.conf
      - ./index.html:/usr/share/nginx/html/index.html
    
  postgres:
    image: postgres:11.4-alpine
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
