version: '3'
services:

#  echo:
#    build: .
#    command: ["-d", "1"]

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_SECRET_ACCESS_KEY=ABCDEF
      - RED=ABCDEF
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./hello.conf:/etc/nginx/conf.d/hello.conf
      - ./index.html:/usr/share/nginx/html/index.html
    
  postgres:
    image: postgres:11.4-alpine
    environment:
      - DB_USER=XXX
      - DB_PASS=YYY
      - RED=ABCDEF
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
